# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'LogInOut' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'logInOut' do
    @driver.get('http://automationpractice.com/index.php')
    @driver.manage.resize_to(1580, 1200)
    @driver.find_element(:link_text, 'Sign in').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('ismrismrd@gmail.com\\n')
    @driver.find_element(:id, 'passwd').click
    @driver.find_element(:id, 'passwd').send_keys('Lozinka01')
    @driver.find_element(:css, '#SubmitLogin > span').click
    @driver.find_element(:link_text, 'Sign out').click
  end
end
