// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void LogInOut() {
    driver.Navigate().GoToUrl("http://automationpractice.com/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1580, 1200);
    driver.FindElement(By.LinkText("Sign in")).Click();
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("ismrismrd@gmail.com\\n");
    driver.FindElement(By.Id("passwd")).Click();
    driver.FindElement(By.Id("passwd")).SendKeys("Lozinka01");
    driver.FindElement(By.CssSelector("#SubmitLogin > span")).Click();
    driver.FindElement(By.LinkText("Sign out")).Click();
  }
}
